# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, to='blog.Category', verbose_name='分类'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
