# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170917_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['pk'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
