# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170917_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, upload_to='cover'),
        ),
    ]
