# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20171015_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_floor',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
