# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_comment_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_floor',
        ),
    ]
