# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_comment_comment_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='floor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
