# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20171201_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_child', to='blog.Comment', verbose_name='父级评论'),
        ),
    ]
