# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20171211_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=50, verbose_name='昵称'),
        ),
    ]
