# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
