# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 04:53
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_remove_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='avatar/default.jpg', upload_to='avatar', verbose_name='头像'),
        ),
    ]
