# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20171211_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='intro',
        ),
    ]
