# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20171225_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=1000, verbose_name='评论内容'),
        ),
    ]
