# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_auto_20171227_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='评论'),
        ),
    ]
