# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 00:25
from __future__ import unicode_literals

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_auto_20171227_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=django_summernote.fields.SummernoteTextField(verbose_name='评论内容'),
        ),
    ]
