# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_auto_20171230_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='分类名'),
        ),
    ]
