# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-20 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_comment_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='page',
        ),
    ]
