# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-21 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_remove_comment_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='page',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='所在页'),
        ),
    ]
